DROP DATABASE IF EXISTS Air6n6; 
CREATE DATABASE Air6n6;
USE Air6n6;

CREATE TABLE Listings (
  listingId INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  basePrice INT NOT NULL
); 

CREATE TABLE Reservations (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user VARCHAR(100) NOT NULL,
  checkin DATE NOT NULL,
  checkout DATE NOT NULL,
  listingId INT NOT NULL,
  FOREIGN KEY (listingId) REFERENCES Listings(listingId)
);